### ISSUE TITLE
Use RadiogridField in one of survey pages?

### ISSUE THREAD

**Issue by yukitakahashi1** [chapkovski/bigfive#1]
Hi Philipp,
I want to use RadiogridField in one of my survey pages. However, when I copy and paste bigfive as an example in one page of my app and run "otree devserver", I've got the following error message:
```
An error occurred.
You may have added a non-nullable field without a default. This typically happens when importing model fields from django instead of otree.
(For technical details about this error, run "otree devserver --verbosity=1")
```
and when I run "otree devserver --verbosity=1", it returns ```SystemExit: 3```. May I ask you what the problem is? My oTree version is 2.5.7. When I run the original bigfive app placed in the same project folder, it runs without any problem.

**Comment by chapkovski** [comment]
just add here null=True
https://github.com/chapkovski/bigfive/blob/71141924b84c7cd7bc4d23a9cd526629a7cf7487/bigfive/models.py#L72

**Comment by yukitakahashi1** [comment]
Worked perfect. Thank you!
